# .travis.yml
#
# Requires the following environment variables to be set:
#   DOCKER_USERNAME
#   DOCKER_PASSWORD

language: python
# See available versions at https://docs.travis-ci.com/user/languages/python/
python:
  - '3.6'
  - '3.7-dev'
  - 'nightly'
# NOTE: We only deploy on ONE of these tests being successful -- see condition below

services:
  - docker

#before_install:
  #- pip install awscli
  #- scripts/travis_install_apex.sh

install:
  - pip3 install --requirement tXenqueue/requirements.txt
  - pip3 install coveralls

# Run the tests first
#  and if they succeed, make the docker image(s)
#   (and check that both succeed)
script:
  - PYTHONPATH="tXenqueue/" coverage run -m unittest discover -s tests/

# Only execute the following instructions in the case of a success
#  (failing at this point won't mark the build as a failure).
# To have `DOCKER_USERNAME` and `DOCKER_PASSWORD` filled
#  you need to either use `travis`' cli and then `travis set ..`
#  or go to the travis page of your repository
#  and then change the environment in the settings pannel.
after_success:
  - coveralls

env:
  global:
    - PYTHONDONTWRITEBYTECODE=true

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh develop
    on:
      branch: develop
      condition: $TRAVIS_PYTHON_VERSION == '3.7-dev'
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh master
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION == '3.7-dev'
